global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: stocksteward-backend
    metrics_path: /api/v1/logs/metrics
    params:
      user_id: ["999"]
    static_configs:
      - targets: ["host.docker.internal:8000"]
